// ============================================================
// JERSEY CATALOG — Edit prices, names, and payment details here
// ============================================================

const PAYMENT_INFO = {
  tillNumber: "XXXXXXX",       // ← REPLACE with your Till number
  phoneNumber: "07XX XXX XXX", // ← REPLACE with your M-Pesa phone number
  accountName: "East Assembly KAG",
  instructions: "Go to M-Pesa → Lipa na M-Pesa → Buy Goods → Enter Till, OR Send Money to the phone number above. Then paste your confirmation message in the form.",
};

const SIZES = ["XS", "S", "M", "L", "XL", "XXL", "3XL"];

const JERSEYS = [
  // ── EPL JERSEYS ──────────────────────────────────────────
  {
    id: 1,
    category: "epl",
    team: "Arsenal",
    league: "Premier League",
    type: "Home",
    season: "2024/25",
    price: 1500,
    emoji: "🔴",
    colors: ["#EF0107", "#FFFFFF"],
    badge: "🏆 Most Popular",
    description: "Iconic red & white home kit. The Gunners' classic look.",
  },
  {
    id: 2,
    category: "epl",
    team: "Manchester City",
    league: "Premier League",
    type: "Home",
    season: "2024/25",
    price: 1500,
    emoji: "🔵",
    colors: ["#6CABDD", "#FFFFFF"],
    badge: "",
    description: "Sky blue home jersey of the reigning champions.",
  },
  {
    id: 3,
    category: "epl",
    team: "Liverpool",
    league: "Premier League",
    type: "Home",
    season: "2024/25",
    price: 1500,
    emoji: "🟥",
    colors: ["#C8102E", "#FFFFFF"],
    badge: "🔥 Hot Pick",
    description: "You'll Never Walk Alone. The Reds' famous home strip.",
  },
  {
    id: 4,
    category: "epl",
    team: "Chelsea",
    league: "Premier League",
    type: "Home",
    season: "2024/25",
    price: 1500,
    emoji: "💙",
    colors: ["#034694", "#FFFFFF"],
    badge: "",
    description: "Chelsea's royal blue home kit. Stamford Bridge faithful.",
  },
  {
    id: 5,
    category: "epl",
    team: "Manchester United",
    league: "Premier League",
    type: "Home",
    season: "2024/25",
    price: 1500,
    emoji: "🔴",
    colors: ["#DA291C", "#FFE500"],
    badge: "",
    description: "The Theatre of Dreams. United's iconic red home jersey.",
  },
  {
    id: 6,
    category: "epl",
    team: "Tottenham Hotspur",
    league: "Premier League",
    type: "Home",
    season: "2024/25",
    price: 1500,
    emoji: "⚪",
    colors: ["#FFFFFF", "#132257"],
    badge: "",
    description: "Spurs' crisp white home kit. Glory glory Tottenham.",
  },
  // ── WORLD CUP JERSEYS ────────────────────────────────────
  {
    id: 7,
    category: "worldcup",
    team: "Brazil",
    league: "World Cup 2026",
    type: "Home",
    season: "2026",
    price: 1500,
    emoji: "🇧🇷",
    colors: ["#009C3B", "#FFDF00"],
    badge: "⭐ 5× Champions",
    description: "The iconic Seleção yellow & green. Most decorated national team.",
  },
  {
    id: 8,
    category: "worldcup",
    team: "Argentina",
    league: "World Cup 2026",
    type: "Home",
    season: "2026",
    price: 1500,
    emoji: "🇦🇷",
    colors: ["#74ACDF", "#FFFFFF"],
    badge: "🏆 Defending Champions",
    description: "Messi's Argentina. The light blue & white stripes of glory.",
  },
  {
    id: 9,
    category: "worldcup",
    team: "France",
    league: "World Cup 2026",
    type: "Home",
    season: "2026",
    price: 1500,
    emoji: "🇫🇷",
    colors: ["#002395", "#FFFFFF"],
    badge: "",
    description: "Les Bleus — deep navy blue powerhouse from Paris.",
  },
  {
    id: 10,
    category: "worldcup",
    team: "Spain",
    league: "World Cup 2026",
    type: "Home",
    season: "2026",
    price: 1500,
    emoji: "🇪🇸",
    colors: ["#AA151B", "#F1BF00"],
    badge: "",
    description: "La Roja's passionate red. Tiki-taka style and substance.",
  },
  {
    id: 11,
    category: "worldcup",
    team: "Germany",
    league: "World Cup 2026",
    type: "Home",
    season: "2026",
    price: 1500,
    emoji: "🇩🇪",
    colors: ["#FFFFFF", "#000000"],
    badge: "",
    description: "Die Mannschaft's classic white. German precision and power.",
  },
  {
    id: 12,
    category: "worldcup",
    team: "Kenya 🦁",
    league: "World Cup 2026",
    type: "Home",
    season: "2026",
    price: 1500,
    emoji: "🇰🇪",
    colors: ["#006600", "#CC0001"],
    badge: "🏠 Support Home!",
    description: "Harambee Stars. Represent Kenya — the pride of our nation!",
  },
];
